@startuml
!pragma teoz true
hide footbox

participant Client1
participant Server
participant Client2

activate Server

Server -> Client1 ++: OfferService()
&Server -> Client2 ++: OfferService()
deactivate Client1
deactivate Client2
deactivate Server

Client2 -> Server ++: SubscribeEventgroup()

Server -> Server ++: updateRegistration()
deactivate Server
Server -> Client2 ++: SubscribeEventgroupAck()
deactivate Client2
Server -> Client2 ++: Event()
deactivate Client2
deactivate Server

activate Client1
Client1 -> Server ++: SubscribeEventgroup()
deactivate Client1
' activate Server

Server -> Server ++: updateRegistration()
deactivate Server
' activate Server
' activate Client1
Server -> Client1 ++: SubscribeEventgroupAck()
deactivate Client1

Server -> Client1 ++: Event()
&Server -> Client2 ++: Event()
deactivate Client1
deactivate Client2

Server -> Client1 ++: Event()
&Server -> Client2 ++: Event()
deactivate Client2
deactivate Server

Client1 -> Server ++: StopSubscribeEventgroup()
deactivate Client1
' deactivate Client1
Server -> Server ++: updateRegistration()
deactivate Server
Server -> Client2 ++: Event()
deactivate Client2
deactivate Server
' activate Client2
' deactivate Client2
' deactivate Server

@enduml