@startuml
!pragma teoz true
hide footbox

participant Server
participant Client

activate Server
Server -> Client ++: OfferService()
deactivate Server
note left
    No registration
end note
Client -> Server ++: SubscribeEventgroup()
deactivate Client
Server -> Server ++: updateRegistration()
deactivate Server
Server -> Client ++: SubscribeEventgroupAck()
deactivate Client
Server -> Client ++: Events()
deactivate Client
Server -> Server ++: linkDown()
Server -> Server ++: deleteRegistrations()
deactivate Server
deactivate Server
Server -> Server ++: linkUp()
deactivate Server
Server -> Client ++: OfferService() [Session ID=1, Reboot=1]
Client -> Server ++: SubscribeEventgroup()
note right
    Reboot 
    detected!
end note
deactivate Client
deactivate Server

Server -> Server ++: updateRegistration()
deactivate Server
Server -> Client ++: SubscribeEventgroupAck()
deactivate Client
Server -> Client ++: Events()
deactivate Client

@enduml